### ISSUE TITLE
how to add salt in authentication

### ISSUE THREAD

**Issue by jdevsean** [jsreport/jsreport-authentication#2]
hi sir,when i enabled authentication in jsreport , whether i can add salt in jsreport to encrypt base64(username,password) ? if can do it , how to do ? thanks!

**Comment by bjrmatos** [comment]
hmm i'm afraid that this is not possible right now, the authentication in jsreport is very simple (Http Basic or POST request to /login), what are you trying to accomplish? are you trying to transfer username and password safely across the network? just note that to do that you should mount jsreport in `https`, rather using a proxy like nginx or configure jsreport to use `https` with `httpsPort` and `certificate` [options](https://jsreport.net/learn/configuration)

**Comment by pofider** [comment]
Additionally to the @bjrmatos  comment:

User's password created through authentication are having its own salt and are stored in hash form.
The admin's password is defined in the raw form in the jsreport config file. You can use your own procedures to encrypt the config file.

**Comment by jdevsean** [comment]
ok,thanks!  but in addtional , i am curious that the how to decode the authentication header in request , which js file , because i find multiple base64.js , i think that the decode work work in one of then or password-hash.js

**Comment by bjrmatos** [comment]
hmm but all of that is handled in `jsreport-authentication` for you, authentication validation is handled by the package, if you are curious see [this](https://github.com/jsreport/jsreport-authentication/blob/master/lib/authentication.js#L38) which under the hood uses passport.js http strategy to decode the authentication header so you won't need to do any of this by your self, or am i missing something that you are trying to do?

**Comment by jdevsean** [comment]
ok , i just want to learn it , because that is my first contact nodejs , thanks for you help.

**Comment by bjrmatos** [comment]
ahh ok, i understand. try to see http://passportjs.org/ for more information or [the exact part that you are looking for](https://github.com/jaredhanson/passport-http/blob/master/lib/passport-http/strategies/basic.js#L68)
