### ISSUE TITLE
Don't require CookieSession

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-authentication#5]
Authentication extension should work just with setting
`
```js
{
  "admin": {
     "username": "admin",
     "password": "password"
   }
}
```

[Reference issue](https://github.com/jsreport/jsreport-dotnet-aspnetcore/issues/4)

**Comment by pofider** [comment]
We decided that cookieSession really must be there as required field.

**Comment by Peter-Optiway** [comment]
But what does it do? What content should it have?
https://jsreport.net/learn/authentication only shows the field but never explains what it is used for????

**Comment by pofider** [comment]
Something like this.... 
The cookie is used with browser-based authentication.
The recipe uses [this package](https://github.com/mozilla/node-client-sessions) which explains it in detail.
```js
"extensions": {
    "authentication" : {
        "cookieSession": {
            "secret": "dasd321as56d1sd5s61vdv32",                  
        },
        "admin": {
            "username" : "admin",
            "password": "password"
        }
    }
}
```
